"""add arm-shop relationship

Revision ID: 0eff5dae314a
Revises: d140757b151d
Create Date: 2022-10-21 21:23:37.340897

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '0eff5dae314a'
down_revision = 'd140757b151d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arminfo', sa.Column('shop_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'arminfo', 'shopinfo', ['shop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'arminfo', type_='foreignkey')
    op.drop_column('arminfo', 'shop_id')
    # ### end Alembic commands ###
