"""add fiscal-shop relationship

Revision ID: 3959a1feea13
Revises: 0eff5dae314a
Create Date: 2022-10-21 21:32:31.090569

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '3959a1feea13'
down_revision = '0eff5dae314a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fiscalinfo', sa.Column('shop_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fiscalinfo', 'shopinfo', ['shop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fiscalinfo', type_='foreignkey')
    op.drop_column('fiscalinfo', 'shop_id')
    # ### end Alembic commands ###
