"""one moe edit relationship entity-shop

Revision ID: 3b139d66f920
Revises: 921b4b0ebd41
Create Date: 2022-10-29 22:17:44.656927

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '3b139d66f920'
down_revision = '921b4b0ebd41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
