"""add shipment to ShopInfo

Revision ID: 3b889765f50d
Revises: c31c6df831d5
Create Date: 2022-10-30 11:20:24.680591

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '3b889765f50d'
down_revision = 'c31c6df831d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopinfo', sa.Column('shop_shipment', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopinfo', 'shop_shipment')
    # ### end Alembic commands ###
