"""add egais fiels in ShopInfo model

Revision ID: 5a4fb7da7018
Revises: 621a9782c5ba
Create Date: 2022-10-30 19:15:20.974553

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '5a4fb7da7018'
down_revision = '621a9782c5ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopinfo', sa.Column('egais_avaliable', sa.Boolean(), nullable=True))
    op.add_column('shopinfo', sa.Column('egais_fsrar_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('shopinfo', sa.Column('egais_gost_key_end_date', sa.DateTime(), nullable=True))
    op.add_column('shopinfo', sa.Column('egais_rsa_key_end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopinfo', 'egais_rsa_key_end_date')
    op.drop_column('shopinfo', 'egais_gost_key_end_date')
    op.drop_column('shopinfo', 'egais_fsrar_id')
    op.drop_column('shopinfo', 'egais_avaliable')
    # ### end Alembic commands ###
