"""edit misprint

Revision ID: 621a9782c5ba
Revises: c4159832c255
Create Date: 2022-10-30 18:46:37.407483

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '621a9782c5ba'
down_revision = 'c4159832c255'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arminfo', 'shop_num')
    op.add_column('fiscalinfo', sa.Column('fiscal_taxcom_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('fiscalinfo', 'fascal_taxcom_name')
    op.drop_column('fiscalinfo', 'shop_num')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fiscalinfo', sa.Column('shop_num', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fiscalinfo', sa.Column('fascal_taxcom_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('fiscalinfo', 'fiscal_taxcom_name')
    op.add_column('arminfo', sa.Column('shop_num', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
