"""add phone remove entity

Revision ID: 80a98143808f
Revises: 3959a1feea13
Create Date: 2022-10-29 17:22:53.475778

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '80a98143808f'
down_revision = '3959a1feea13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopinfo', sa.Column('shop_phone_person', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('shopinfo', sa.Column('shop_phone_corp', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('shopinfo', 'shop_entity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopinfo', sa.Column('shop_entity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('shopinfo', 'shop_phone_corp')
    op.drop_column('shopinfo', 'shop_phone_person')
    # ### end Alembic commands ###
