"""edit relationship entity-shop

Revision ID: 921b4b0ebd41
Revises: 80a98143808f
Create Date: 2022-10-29 22:10:30.070737

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '921b4b0ebd41'
down_revision = '80a98143808f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
