"""remove shop_num at ArmInfo and FiscalInfo

Revision ID: ba72a72134ad
Revises: 3b889765f50d
Create Date: 2022-10-30 11:24:49.973517

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'ba72a72134ad'
down_revision = '3b889765f50d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
