"""edit other relationship

Revision ID: c31c6df831d5
Revises: 3b139d66f920
Create Date: 2022-10-29 22:22:35.899303

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'c31c6df831d5'
down_revision = '3b139d66f920'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
