"""edit misprint in fiscal_taxcom_name

Revision ID: c4159832c255
Revises: ba72a72134ad
Create Date: 2022-10-30 18:03:27.556406

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'c4159832c255'
down_revision = 'ba72a72134ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
