"""first

Revision ID: cd84c64c18da
Revises: 
Create Date: 2022-10-19 20:24:53.328656

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'cd84c64c18da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arminfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_num', sa.Integer(), nullable=True),
    sa.Column('arm_comp', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('arm_os', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('arm_shtrih_ver', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('arm_pos_num', sa.Integer(), nullable=True),
    sa.Column('arm_permit', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entityinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entity_inn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fiscalinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_num', sa.Integer(), nullable=True),
    sa.Column('fiscal_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fiscal_fabric_num', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fiscal_reg_num', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fascal_taxcom_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fiscal_taxcom_end_date', sa.DateTime(), nullable=True),
    sa.Column('fiscal_fn_num', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fiscal_fn_period', sa.Integer(), nullable=True),
    sa.Column('fiscal_fn_end_day', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_num', sa.Integer(), nullable=True),
    sa.Column('shop_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shop_status', sa.Boolean(), nullable=True),
    sa.Column('shop_entity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shop_kpp', sa.Integer(), nullable=True),
    sa.Column('cigarettes', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopinfo')
    op.drop_table('fiscalinfo')
    op.drop_table('entityinfo')
    op.drop_table('arminfo')
    # ### end Alembic commands ###
