"""add relationship

Revision ID: d140757b151d
Revises: cd84c64c18da
Create Date: 2022-10-21 20:52:25.689534

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'd140757b151d'
down_revision = 'cd84c64c18da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopinfo', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shopinfo', 'entityinfo', ['entity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shopinfo', type_='foreignkey')
    op.drop_column('shopinfo', 'entity_id')
    # ### end Alembic commands ###
